/**
 * API-Katalog — automatisch generiert.
 * `node scripts/generate-api-catalog.mjs` oder `npm run generate:api-catalog`
 */

export type ApiCatalogEntry = {
  /** Vollständiger Pfad inkl. /api
   * Dynamische Segmente: :param (aus [param] im Dateisystem).
   */
  path: string;
  methods: readonly string[];
  /** Quelldatei relativ zum Repo-Root */
  source: string;
  /** Kurzbeschreibung (Deutsch), aus JSDoc und/oder manueller Tabelle */
  description: string;
};

export const API_CATALOG_GENERATED_AT = "2026-06-30T18:14:11.802Z" as const;

export const API_CATALOG: readonly ApiCatalogEntry[] = [
  { path: "/api/admin/settings", methods: ["GET", "PUT"], source: "functions/api/admin/settings.ts", description: "Admin: listet alle Zeilen der Tabelle `settings` im D1-Binding `configs` (GET) bzw. upsert einer Zeile mit id, config (JSON), optional description (PUT). Zugriff nur mit freigegebenem `/admin-settings` in der Sicherheitsstufe." },
  { path: "/api/analytics/_diag", methods: ["GET"], source: "functions/api/analytics/_diag.ts", description: "Diagnose für alle genutzten Analytics-Quellen (primär + optional Konto 2). GET /api/analytics/_diag Nur für eingeloggte Benutzer." },
  { path: "/api/analytics/customer-keys", methods: ["GET"], source: "functions/api/analytics/customer-keys.ts", description: "Analytics-Auswertungen zur Kunden-API über Analytics Engine: Parameter kind (z. B. overview, Zeitreihen, Top-Listen, key-detail) und mode customers/oneauto, plus Zeitraum- und Key-Filter." },
  { path: "/api/analytics/oneauto-reports", methods: ["GET"], source: "functions/api/analytics/oneauto-reports.ts", description: "Monatliche Abrechnung für den Oneauto-Key. GET /api/analytics/oneauto-reports?months=12 Liefert pro Monat (UTC, beginnend am 1.) die Anzahl der echten Bild-Views (blob5 ist View-Name, kein list_… und kein check_views), den GBP-Betrag (views * 0.02) und den EUR-Gegenwert anhand des Monatsend-Wechselkurses von frankfurter.app (ECB-Daten). Wenn der Wechselkurs nicht abrufbar ist, wird `eur` auf `null` gesetzt und der Grund mitgeschickt – der Monat wird trotzdem angezeigt. Holt einen GBP→EUR-Wechselkurs zu einem Datum." },
  { path: "/api/assets", methods: ["GET"], source: "functions/api/assets/index.ts", description: "Asset-Listen-Endpoint — direkt gegen R2. GET /api/assets?folder=&q=&limit=&offset=&sort= → { rows, total, limit, offset, folder, public_base } Verhalten: - Ohne `q`: listet die DIREKTEN Kinder von `folder` (delimited list). Sub-Folders erscheinen als `kind:\"folder\"`-Einträge. - Mit `q`: rekursive Suche über alle Schlüssel mit Prefix `folder`, filtert nach Substring (case-insensitive) im Namen. - `sort`: \"newest\" (default, nach `uploaded`), \"name\", \"size\". - `limit`/`offset`: clientseitige Slicing-Parameter (R2 pagi" },
  { path: "/api/assets/folders", methods: ["GET", "POST", "DELETE"], source: "functions/api/assets/folders.ts", description: "Folder-Operationen — abgeleitet aus den R2-Object-Keys. GET /api/assets/folders → { folders: { path, name, parent, count }[] } Listet alle bekannten Ordnerpfade. Ein Ordner existiert, sobald mindestens ein Objekt mit dem entsprechenden Prefix vorliegt (inkl. der `<folder>/.keep`-Marker für leere Ordner). POST /api/assets/folders { path: \"email/team\" } → 201 mit dem Marker-Asset (`<folder>/.keep`) Legt einen leeren Ordner an, indem ein 0-Byte-Marker `<path>/.keep` mit `customMetadata.foldermarker=1` hochgeladen wird" },
  { path: "/api/assets/item", methods: ["GET", "PATCH", "DELETE"], source: "functions/api/assets/item.ts", description: "Einzel-Asset-Operationen — Schlüssel via Query-Param `?key=`, weil R2-Keys Slashes enthalten und Pages-Functions Pfad-Parameter mit Slashes nicht zuverlässig durchreichen. GET /api/assets/item?key=email/banner.png → Asset-Zeile PATCH /api/assets/item?key=email/banner.png { name?, folder?, title?, alt_text?, description? } → 200 mit neuem Asset (Bei `name`/`folder`-Änderung wird in R2 per copy+delete umgezogen.) DELETE /api/assets/item?key=email/banner.png → 204 Datei-Metadaten (`alt_text`, `description`, `uploaded_" },
  { path: "/api/assets/upload", methods: ["POST"], source: "functions/api/assets/upload.ts", description: "Asset-Upload — schreibt direkt in den R2-Bucket `env.assets`. POST /api/assets/upload (multipart/form-data) Felder: - file (Pflicht) - folder (optional, default \"\") - name (optional, sonst aus file.name abgeleitet) - title (optional → customMetadata, CMS-Anzeigename) - alt_text (optional → customMetadata) - description (optional → customMetadata) - img_w, img_h (optional, Pixel → Metadata für CMS-Tabelle) - status (optional, `draft`|`published`, default published) → 201 mit der vollständigen Asset-Zeile" },
  { path: "/api/billing/payment-link", methods: ["POST"], source: "functions/api/billing/payment-link.ts", description: "POST /api/billing/payment-link Body: { \"paymentLinkId\": \"plink_…\", \"metadata\": { \"price_id\": \"plan_test\", … } } Merged mit bestehenden Metadaten am Payment Link." },
  { path: "/api/billing/payment-link-archive", methods: ["POST"], source: "functions/api/billing/payment-link-archive.ts", description: "POST /api/billing/payment-link-archive Setzt `active` am Payment Link: `false` = archivieren (deaktivieren), `true` = wieder aktivieren. Stripe löscht Payment Links nicht – es gibt nur aktiv/inaktiv." },
  { path: "/api/billing/payment-links", methods: ["GET", "POST"], source: "functions/api/billing/payment-links.ts", description: "POST /api/billing/payment-links Legt einen neuen Payment Link in Stripe an; Metadaten `price_id` = `planKey`. Preis: entweder `stripePriceId` (z. B. aus API-Auswahl) oder im Plan-JSON `stripe_price_id`. Wird `stripePriceId` mitgeschickt, wird sie zusätzlich im Plan-KV gespeichert. GET /api/billing/payment-links Listet Stripe Payment Links (Metadaten inkl. price_id → KV-Plan-Key)." },
  { path: "/api/billing/plans", methods: ["GET", "PUT"], source: "functions/api/billing/plans.ts", description: "GET /api/billing/plans Ohne Query: alle Keys auflisten. ?key=plan_test: vollständigen JSON-Wert lesen. PUT /api/billing/plans Body: { \"key\": \"plan_test\", \"value\": { ... } } – ersetzt den KV-Wert." },
  { path: "/api/billing/stripe-prices", methods: ["GET"], source: "functions/api/billing/stripe-prices.ts", description: "GET /api/billing/stripe-prices Aktive Stripe-Preise (mit Produktname) für die Payment-Link-Erstellung." },
  { path: "/api/cms/content-models", methods: ["GET", "POST"], source: "functions/api/cms/content-models.ts", description: "CMS — Content-Modelle (D1 `website` → `cms_content_models`). GET /api/cms/content-models?q=&limit=&offset= POST /api/cms/content-models { id?, key, description?, schema_json } (nur ab Sicherheitsstufe 8, siehe `assertCmsModelWriteAllowed`) Migration: d1/migrations/0013_cms_content.sql" },
  { path: "/api/cms/content-models/:id", methods: ["GET", "PUT", "DELETE"], source: "functions/api/cms/content-models/[id].ts", description: "CMS — ein Content-Modell. GET /api/cms/content-models/:id PUT /api/cms/content-models/:id { key?, description?, schema_json? } (nur ab Sicherheitsstufe 8) DELETE /api/cms/content-models/:id (ab Sicherheitsstufe 9)" },
  { path: "/api/cms/contents", methods: ["GET", "POST"], source: "functions/api/cms/contents.ts", description: "CMS — Content-Einträge (D1 `website` → `cms_contents`). GET /api/cms/contents?content_model_id=&status=&locale=&q=&scheduled_month=YYYY-MM&updated_by_me=1&limit=&offset= POST /api/cms/contents { id?, content_model_id, payload_json, status?, locale?, scheduled_publish_at? } `last_updated_by` setzt die API aus der Session (Benutzername, sonst User-ID). Antwort-Zeilen können `last_updater_profilbild` enthalten (Lookup in `user`, D1 `env.user`)." },
  { path: "/api/cms/contents/:id", methods: ["GET", "PUT", "DELETE"], source: "functions/api/cms/contents/[id].ts", description: "CMS — ein Content-Eintrag. GET /api/cms/contents/:id PUT /api/cms/contents/:id { content_model_id?, payload_json?, status?, locale?, scheduled_publish_at? } DELETE /api/cms/contents/:id" },
  { path: "/api/configs/active-controll-mode", methods: ["GET"], source: "functions/api/configs/active-controll-mode.ts", description: "GET /api/configs/active-controll-mode Liest `settings.config` für `id = 'active_controll_mode'` aus D1-Binding `configs`. Liefert eine Map mode → boolean, die im Frontend steuert, welche Modi (Korrektur, Skalierung, …) im Modus-Dropdown sichtbar sind. Antwort: ```json { \"modes\": { \"correction\": true, \"scaling\": true, \"shadow\": false, \"transparency\": false }, \"_meta\": { \"source\": \"database\" | \"default\", \"configsBound\": true } } ```" },
  { path: "/api/configs/controll-buttons", methods: ["GET"], source: "functions/api/configs/controll-buttons.ts", description: "GET /api/configs/controll-buttons Liest `settings.config` für `id = 'controll_buttons'` aus D1-Binding `configs`." },
  { path: "/api/configs/controll-status", methods: ["POST"], source: "functions/api/configs/controll-status.ts", description: "POST /api/configs/controll-status — D1 `vehicledatabase` → `controll_status`. Upsert … Sonderaktion delete_in_progress löscht bei check=1 oder bei nicht freigegebener correction-Zeile (404 / 409). Sonderaktion delete_all_for_vehicle löscht alle Einträge zu einer vehicle_id ({ deleted })." },
  { path: "/api/configs/first-views", methods: ["GET"], source: "functions/api/configs/first-views.ts", description: "GET /api/configs/first-views Liest `settings.config` für `id = 'first_views'`. Liefert die Liste der Ansichten, die zuerst bearbeitet werden müssen. Antwort: ```json { \"views\": [\"front\",\"rear\",\"right\",\"left\", …], \"_meta\": { \"source\": \"database\" | \"default\", \"configsBound\": true } } ```" },
  { path: "/api/configs/generation-views", methods: ["GET"], source: "functions/api/configs/generation-views.ts", description: "GET /api/configs/generation-views Liest `settings.config` für `id = 'generation_views'` aus D1-Binding `configs`. Liefert eine Map view-slug → boolean. Slugs mit `true` dürfen im UI als „+\"-Button erscheinen, wenn das Fahrzeug die Ansicht noch nicht hat. Antwort: ```json { \"views\": { \"front\": true, \"rear\": true, \"steeringwheel\": false, … }, \"_meta\": { \"source\": \"database\" | \"default\", \"configsBound\": true } } ```" },
  { path: "/api/configs/google-image-search", methods: ["GET"], source: "functions/api/configs/google-image-search.ts", description: "GET /api/configs/google-image-search Liest `settings.config` für `id = 'google_image_search'`. Liefert das Template, das im Frontend zur Erzeugung der Google-Bildersuche-URL benutzt wird. Antwort: ```json { \"template\": \"Schaue mir bilder von einem {{marke}} {{model}} …\", \"_meta\": { \"source\": \"database\" | \"default\", \"configsBound\": true } } ```" },
  { path: "/api/configs/inside-views", methods: ["GET"], source: "functions/api/configs/inside-views.ts", description: "GET /api/configs/inside-views `settings.config` für `id = 'inside_views'`. ```json { \"views\": [\"dashboard\", \"steeringwheel\"], \"_meta\": { \"source\": \"database\" | \"default\", \"configsBound\": true } } ```" },
  { path: "/api/configs/preview-images", methods: ["GET"], source: "functions/api/configs/preview-images.ts", description: "GET /api/configs/preview-images Liest `settings.config` für `id = 'preview_images'` aus D1-Binding `configs`. Liefert eine Map view-slug → URL. Antwort: ```json { \"images\": { \"front\": \"https://…\", \"rear\": \"https://…\", … }, \"_meta\": { \"source\": \"database\" | \"default\", \"configsBound\": true } } ``` Das Frontend lädt die Map einmalig pro Session (lazy beim ersten Preview-Click) und hält sie im React-State; ein zusätzlicher HTTP-Cache ist daher nicht nötig." },
  { path: "/api/crm/customers", methods: ["GET", "POST", "PUT"], source: "functions/api/crm/customers.ts", description: "CRM-Kunden — Tabelle `customers` in derselben D1-DB wie `submissions` (Binding `website`). GET /api/crm/customers?q=&limit=&offset=&status=&location= POST /api/crm/customers { id?, email, company?, status?, location? } PUT /api/crm/customers { id, email?, company?, status?, location? } Landeskürzel liegt in der Spalte `location` (ISO-3166-Alpha-2). Für ältere Installationen wird `standort` noch als DB-Spalte und Body-Alias unterstützt. JSON-Antwort nutzt immer `location` (leerer String = nicht gesetzt)." },
  { path: "/api/customers/keys", methods: ["GET", "PUT"], source: "functions/api/customers/keys.ts", description: "GET /api/customers/keys `?key=VI-…`: vollständigen Wert lesen. `?map=email`: { map: { [key]: email }, is_test_key: { [key]: boolean } } (alle Keys in `is_test_key`; in `map` nur Keys mit E-Mail). `?view=customer`: nur Keys ohne Kundentest-Plan (kein \"test\" in plan_id / plan_name). `?view=test`: nur Kundentest-Keys (s. `isTestKeyPlanName`). `?view=all` oder ohne view: vollständige Liste (Rückwärtskompatibilität). Ohne `key`/`map`: Keys + Summary (Email, plan_id, …) gemäß `view`." },
  { path: "/api/databases/car-brands", methods: ["GET"], source: "functions/api/databases/car-brands.ts", description: "GET /api/databases/car-brands Liefert die Liste der angebotenen Marken — holt sie serverseitig über die Kunden-API (`/api/brands`, interner Voll-Key) und liefert nur die normalisierten Markennamen aus. Lange gecacht (Marken ändern sich selten). Öffentlich (in der Middleware freigeschaltet), damit auch der Demo-Link sie ohne Login zeigen kann — es sind reine Marketing-Daten (keine Secrets)." },
  { path: "/api/databases/car-control", methods: ["GET", "POST"], source: "functions/api/databases/car-control.ts", description: "Kontroll-Plattform NEUES System — Quell-Bild-Freigabe. GET /api/databases/car-control → offene Autos (kontrolliert=0) zum Prüfen POST /api/databases/car-control → Aktion: freigeben / on-hold / Fehler Im neuen System ist Kontrolle = ein Mensch gibt das QUELL-Bild frei (`kontrolliert 0 → 1`); danach übernimmt der Motor (Freistellen, Skalieren, Schatten) automatisch. „Offen\" = Quell-Zeilen mit `kontrolliert=0` (transparent=0, shadow=0). Bilder zeigt das Frontend über `/api/databases/car-control-image?key=…` (ID-basier" },
  { path: "/api/databases/car-control-image", methods: ["GET"], source: "functions/api/databases/car-control-image.ts", description: "GET /api/databases/car-control-image?key=source/<id> Liefert ein ID-basiertes Bild aus dem NEUEN Bildspeicher (R2 `vehicleimages`) für die neue Kontroll-Ansicht. Der Schlüssel kommt aus der Datenbank (`original_r2_key` / `r2_key`), z. B. `source/01KVJ…`. Nur für angemeldete Dashboard-Nutzer. Der Schlüssel wird streng validiert (nur `source/`, `scaled/`, `shadow/` + ULID-Zeichen) — kein beliebiger R2-Zugriff. Bild wird in Originalgröße ausgeliefert + edge-gecacht." },
  { path: "/api/databases/car-database", methods: ["GET"], source: "functions/api/databases/car-database.ts", description: "GET /api/databases/car-database Liest die NEUE Fahrzeug-Datenbank (`cardb` → Tabelle `fahrzeugliste`, eine Zeile je Bild-Variante) für die „Car Database\"-Übersicht. ?mode=overview → Kennzahlen + Daten für Grafiken ?mode=detail → ein Auto im Detail: alle Farben + alle Ansichten (pro Ansicht aggregiert) für die Detail-Ansicht (sonst, list) → gefilterte, paginierte Liste PRO AUTO (marke|modell|jahr|body|trim|farbe aggregiert) List-Parameter: q, marke, farbe, format, view, status status ∈ open|done|error|hold|not_rende" },
  { path: "/api/databases/car-generate", methods: ["GET", "POST"], source: "functions/api/databases/car-generate.ts", description: "Bild-Generierung „Auto erstellen\" über kie.ai (nano-banana-2). Ersetzt den toten Google-AI-Gateway-Weg. POST /api/databases/car-generate → startet einen Generier-Auftrag, gibt { taskId } zurück. Body: { marke, modell, jahr, view, images?: string[] } images = optionale Referenz-Bild-URLs (für Bild→Bild / konsistente Ansichten). GET /api/databases/car-generate?taskId=… → Status pollen: { state: \"waiting\"|\"success\"|\"fail\", imageUrl?: string, error?: string } Nur für angemeldete Dashboard-Nutzer. Schlüssel: Pages-Secre" },
  { path: "/api/databases/car-generate-save", methods: ["POST"], source: "functions/api/databases/car-generate-save.ts", description: "POST /api/databases/car-generate-save Speichert generierte Auto-Bilder ins NEUE System: pro Ansicht das Bild nach R2 `vehicleimages` als `source/<ulid>` + eine Zeile in `fahrzeugliste` (transparent=0, shadow=0, kontrolliert=0 → „offen zur Kontrolle\"). Danach erscheinen sie in der neuen Kontroll-Ansicht (/control-platform/neu); nach Freigabe (kontrolliert=1) übernimmt der Motor Freistellen/Skalieren/Schatten. Body: { marke, modell, jahr, body?, trim?, farbe?, items: [{view, imageUrl}] } imageUrl = öffentliche URL (z" },
  { path: "/api/databases/car-generate-test", methods: ["POST"], source: "functions/api/databases/car-generate-test.ts", description: "POST /api/databases/car-generate-test TEST-Endpoint: Bild→Bild-Generierung. Nimmt hochgeladene Referenzfotos eines Autos (Base64) + eine Ziel-Ansicht und versucht über Workers AI (google/nano-banana-2, AI-Gateway „default\") unsere Studio-Ansicht zu erzeugen. Gedacht für ältere Modelle, die die KI nicht kennt. WICHTIG: Es wird NICHTS gespeichert (kein R2, keine DB) — das Ergebnis wird nur temporär als Data-URL zurückgegeben und im Frontend angezeigt." },
  { path: "/api/databases/car-image", methods: ["GET"], source: "functions/api/databases/car-image.ts", description: "GET /api/databases/car-image Thumbnail-Proxy für die Car-Database-Tabelle. Holt das Bild einer Ansicht über die bestehende Kunden-API (api.vehicleimagery.com) mit einem INTERNEN Voll-Key (`CAR_DB_API_KEY`) und liefert es verkleinert aus. Aktuell bedient die Kunden-API noch das ALTE System (vehicleimagery_public_storage); sobald sie aufs neue System (fahrzeugliste/source) umgestellt ist, liefert derselbe Proxy automatisch die neuen Bilder — ohne Änderung hier. Caching: Das Bild ist für alle Nutzer identisch → es wir" },
  { path: "/api/databases/car-incomplete", methods: ["GET"], source: "functions/api/databases/car-incomplete.ts", description: "GET /api/databases/car-incomplete?q=&only=incomplete|all&limit=&offset= Finder fürs NEUE System: Autos in `fahrzeugliste`, bei denen nicht alle 8 Standard-AUSSEN-Ansichten gerendert sind (r2_key vorhanden). Pro Auto (marke|modell|jahr|body|trim|farbe): welche Ansichten da/fehlend sind. Die Nach-Generierung läuft im Frontend über /api/databases/car-generate (kie.ai) + /api/databases/car-generate-save (→ kontrolliert=0 → neue Kontrolle)." },
  { path: "/api/databases/car-stats", methods: ["GET"], source: "functions/api/databases/car-stats.ts", description: "GET /api/databases/car-stats Liefert ein paar Eckdaten der Bild-API für die Demo — aktuell die Gesamtzahl der Bilder (eine Zeile je Bild in `fahrzeugliste`, Binding `cardb`). Öffentlich (Middleware-Allowlist), damit auch der Demo-Link es zeigen kann — reine Zahl, kein Secret. 1 Stunde gecacht." },
  { path: "/api/databases/demo-link", methods: ["GET", "POST", "DELETE"], source: "functions/api/databases/demo-link.ts", description: "GET/POST/DELETE /api/databases/demo-link Admin-Verwaltung der Kunden-Demo-Links (nur angemeldete Dashboard-Nutzer; reitet auf der bestehenden `/api/databases/*`-Freigabe der Car Database). GET → Liste aller Links (mit Status/Ablauf/Nutzung) POST → neuen Link erzeugen { name, allowedColors[], featured[], showroom[], expiresInDays } DELETE ?token=… → Link sperren (revoke)" },
  { path: "/api/databases/demo-link-public", methods: ["GET"], source: "functions/api/databases/demo-link-public.ts", description: "GET /api/databases/demo-link-public?token=dl_… ÖFFENTLICH (in der Middleware von der Session-Pflicht ausgenommen). Liefert die Konfiguration eines gültigen Demo-Links (Name, Ablauf, erlaubte Farben + Fahrzeug-Snapshot), damit die öffentliche Demo-Seite `/d/:token` ohne Login rendern kann. Ungültig/abgelaufen/gesperrt → `{ ok: false }` (HTTP 200, damit die Seite eine saubere „Link abgelaufen\"-Meldung zeigen kann)." },
  { path: "/api/databases/test-key-activate", methods: ["GET"], source: "functions/api/databases/test-key-activate.ts", description: "GET /api/databases/test-key-activate?go=1 EINMALIG — legt einen manuellen Test-Key in der KV `customer_keys` an, mit hartem Ablauf heute 22:00 deutscher Zeit (native KV-Expiration). Der Umfang wird von den ECHTEN automatischen Test-Keys GEKLONT (häufigste Umfang- Signatur unter allen „test\"-Keys) — so passt der Umfang exakt, ohne die Vorlage des Keymanager-Workers zu kennen. Gebraucht, weil das CLI-Cloudflare-Token gerade fehlt; der eingeloggte Nutzer aktiviert per Klick. Danach wieder entfernen." },
  { path: "/api/databases/vehicle-imagery", methods: ["GET", "PUT", "DELETE"], source: "functions/api/databases/vehicle-imagery.ts", description: "GET /api/databases/vehicle-imagery PUT /api/databases/vehicle-imagery D1 `vehicledatabase` → `vehicleimagery_public_storage` GET: Query `id=` → ein Datensatz { row, cdnBase, imageUrlQuery } GET: sonst Liste: q, limit, offset, active=all|1|0, genehmigt=all|1|0 (optional), views_mode=korrektur|transparenz|skalierung|schatten (optional, filtert Feld `views`): transparenz: enthält `#trp`, skalierung: enthält `#skaliert` (inkl. `#skaliert_weiß` usw.), schatten: `#shadow`, korrektur: keines dieser Muster, strukturierte F" },
  { path: "/api/databases/vehicle-imagery-controlling", methods: ["GET", "POST", "PUT", "DELETE"], source: "functions/api/databases/vehicle-imagery-controlling.ts", description: "GET /api/databases/vehicle-imagery-controlling PUT /api/databases/vehicle-imagery-controlling D1 `vehicledatabase` → `vehicleimagery_controlling_storage` Gleiche Felder wie Public-Storage, ohne Spalte `genehmigt`. GET/PUT-Verhalten entspricht `vehicle-imagery.ts`, jedoch ohne genehmigt-Parameter/Filter/Suche-Spalte. CDN-Basis für `cdnBase`: `IMAGE_CDN_CONTROLLING_BASE` oder Default `https://vehicleimagery-controlling.vehicleimagery.com` (Pfad `v1/…` wie beim Public-CDN). Detail-Antwort (`?id=`) liefert zusätzlich `" },
  { path: "/api/databases/vehicle-imagery-incomplete", methods: ["GET", "POST"], source: "functions/api/databases/vehicle-imagery-incomplete.ts", description: "Finder + Nach-Generierung für Live-Autos mit fehlenden AUSSEN-Ansichten. GET /api/databases/vehicle-imagery-incomplete?q=&only=incomplete|all&limit=&offset= Liest den LIVE-Bestand (`vehicleimagery_public_storage`, active=1) und zählt die 8 Standard-Außen-Ansichten im `views`-Feld. Liefert pro Auto: vorhandene/fehlende Ansichten + ob ein Controlling-Zwilling existiert. POST /api/databases/vehicle-imagery-incomplete Body: { controllingId, views: string[] } Legt für die genannten (fehlenden) Außen-Ansichten je einen R" },
  { path: "/api/databases/vehicle-imagery-rescale", methods: ["POST"], source: "functions/api/databases/vehicle-imagery-rescale.ts", description: "POST /api/databases/vehicle-imagery-rescale Skaliert die Außen-Ansichten eines Produktions-Autos NEU — mit einer benutzerdefinierten Höhe — und schleust die Ergebnisse über den normalen Kontroll-Ablauf (Modus „Skalierung\"). Sie müssen dort erst freigegeben werden, bevor sie die Produktionsbilder überschreiben (das übernimmt der bestehende `finalizeScaling`-Schritt anhand des identischen Bild-Pfads). Body: { id: number (Produktions-/Public-ID), hohe: number } Ablauf: 1. Produktions-Auto laden (`vehicleimagery_public" },
  { path: "/api/databases/vehicle-imagery-status", methods: ["GET"], source: "functions/api/databases/vehicle-imagery-status.ts", description: "GET /api/databases/vehicle-imagery-status Aggregierte Kennzahlen zu `vehicleimagery_public_storage` (nur aktive Zeilen). Ansichten werden wie in `_lib/vehicleImageryCatalog.parseViewNamesFromViewsField` aus dem Feld `views` geparst." },
  { path: "/api/emails/jobs", methods: ["GET", "POST"], source: "functions/api/emails/jobs.ts", description: "Email-Jobs (Versand-Queue / -Log). GET /api/emails/jobs?q=&status=&template_id=&from=&to=&limit=&offset= → { rows: EmailJobRow[], total, limit, offset, statusCounts, hint? } Listenzeilen enthalten Tracking-Aggregate (opens / clicks / first_open_at). POST /api/emails/jobs (Email manuell) Body: { recipient_email, recipient_data?, template_id?, custom_subject?, custom_body_html?, scheduled_at?, from_email? } → 201 mit voller Zeile Schreibt einen `pending`-Job in die Tabelle. Den Versand übernimmt der externe Mail-Work" },
  { path: "/api/emails/jobs/:id", methods: ["GET"], source: "functions/api/emails/jobs/[id].ts", description: "Email-Jobs — Einzelner Job + Tracking-Zusammenfassung. GET /api/emails/jobs/<id> → EmailJobFull (inkl. raw `custom_body_html`, voller `recipient_data`, Tracking-Aggregate sowie Top-Click-URLs / Top-Länder) Schreibende Verben: 405. Bearbeitung erfolgt ausschließlich durch den externen Mail-Worker." },
  { path: "/api/emails/jobs/:id/events", methods: ["GET"], source: "functions/api/emails/jobs/[id]/events.ts", description: "Tracking-Events eines einzelnen Email-Jobs (READ-ONLY). GET /api/emails/jobs/<id>/events?q=&event_type=&limit=&offset= → { rows: TrackingEventRow[], total, limit, offset, eventCounts } Wird vom Detail-Panel der Email-Logs-Seite benutzt: dort steht eine suchbare, paginierte Tabelle aller Pixel-Opens und Click-Events des gewählten Jobs." },
  { path: "/api/emails/template-ai", methods: ["GET", "POST"], source: "functions/api/emails/template-ai.ts", description: "Workers AI: Chat-Hilfe für E-Mail-HTML im Dashboard. GET /api/emails/template-ai → { models: { id, label }[], defaultModel } POST /api/emails/template-ai Body: { model?, currentHtml?, messages: { role, content }[] } → { reply, html|null, model } Binding: Pages → Workers AI als `workersai` oder `AI` (siehe getWorkersAiBinding). Provider-Modelle (`openai/…`, `anthropic/…`, …): zusätzlich Environment Variable `AI_GATEWAY_ID` = Name eines AI Gateway im Account (drittes Argument zu `AI.run`, siehe Cloudflare-Doku)." },
  { path: "/api/emails/templates", methods: ["GET", "POST"], source: "functions/api/emails/templates.ts", description: "Email-Templates — Liste & Anlegen. GET /api/emails/templates?q=&limit=&offset= → { rows: { id, subject, updated_at, length }[], total, limit, offset } POST /api/emails/templates { id, subject?, body_html?, copy_from_id? } → 201 mit voller Zeile Tabelle `email_templates` liegt in derselben D1 (`env.website`) wie `customers` und `submissions`. Migration: d1/migrations/0007_email_templates.sql. Schema (unverändert, ohne MJML-Spalte): id, subject, body_html, updated_at. Der Bearbeitungs-State des visuellen Editors (Unl" },
  { path: "/api/emails/templates/:id", methods: ["GET", "PUT", "DELETE"], source: "functions/api/emails/templates/[id].ts", description: "Email-Templates — Einzelne Vorlage. GET /api/emails/templates/:id → volle Zeile PUT /api/emails/templates/:id { subject?, body_html?, new_id? } → 200 DELETE /api/emails/templates/:id → 204 Tabelle `email_templates` (siehe d1/migrations/0007_email_templates.sql) liegt im D1-Binding `website` (zusammen mit `customers`/`submissions`). Optional: id rename. Wenn gesetzt und != alte id, wird umbenannt." },
  { path: "/api/emails/timeline", methods: ["GET"], source: "functions/api/emails/timeline.ts", description: "Email-Timeline — vermischter Live-Feed aller Events. GET /api/emails/timeline ?q=…&kind=created|sent|failed|open|click&status=… &from=ISO&to=ISO&limit=&offset= Setzt zusammen: - Job-Lebenszyklus aus `email_jobs`: * `created` — Job angelegt (created_at) * `sent` — Job vom Mail-Worker versendet (sent_at) * `failed` — Job mit Status='failed' (created_at als Best-Guess, kein dedizierter `failed_at`) - Tracking aus `email_tracking`: * `open` / `click` — pro Event ein Eintrag Ergebnis ist nach Datum absteigend sortiert (" },
  { path: "/api/emails/tracking", methods: ["GET"], source: "functions/api/emails/tracking.ts", description: "Globale Tracking-Statistik über alle Email-Jobs. GET /api/emails/tracking?from=&to= → { range: { from, to }, totals: { jobs_total, jobs_sent, jobs_with_open, jobs_with_click, opens_total, clicks_total, unique_open_jobs, unique_click_jobs, unique_ips, open_rate, click_rate, click_to_open_rate, first_open_at, last_event_at }, by_day: [{ day, opens, clicks }], by_hour: [{ hour: 0..23, opens, clicks }], top_links: [{ link_url, count }], top_countries: [{ country, count }], top_cities: [{ city, country, count }], top_jo" },
  { path: "/api/intern-analytics/controll-jobs", methods: ["GET", "POST"], source: "functions/api/intern-analytics/controll-jobs.ts", description: "GET /api/intern-analytics/controll-jobs D1 `vehicledatabase` → Tabelle `controll_status` (Korrektur-Jobs). Query: check=all|0|1|2|3 vehicle_id= q= limit= offset= job_check: 0 offen, 1 in Bearbeitung, 2 korrekt, 3 fehlgeschlagen POST /api/intern-analytics/controll-jobs Body: { action: \"reset-check\", from: 1 | 3 } Setzt alle Zeilen mit `check = from` auf `check = 0` zurück und aktualisiert `updated_at`. Antwort: { changed: number, from, to: 0 } { action: \"delete-check\", from: 1 | 3 } Löscht alle Zeilen mit `check = f" },
  { path: "/api/intern-analytics/controll-platform-action", methods: ["POST"], source: "functions/api/intern-analytics/controll-platform-action.ts", description: "POST /api/intern-analytics/controll-platform-action Schreibt einen Datenpunkt in `env.controll_analytics` (Analytics Engine). Body: { actionLabel, viewsModeLabel, imageKey?, clientRttMs?, metaJson? }" },
  { path: "/api/intern-analytics/controlling", methods: ["GET"], source: "functions/api/intern-analytics/controlling.ts", description: "GET /api/intern-analytics/controlling Liefert Auswertung der AE-Tabelle `controll_platform_logs`. Query-Parameter: from, to – YYYY-MM-DD HH:MM:SS (Standard: letzte 7 Tage) gapMinutes – Sessions-Trennung (Standard: 5) limit – max. Zeilen aus AE (Standard: 100000, max. 150000) blob4 – nonempty | hex32 | all (Standard: nonempty)" },
  { path: "/api/intern-analytics/diag", methods: ["GET"], source: "functions/api/intern-analytics/diag.ts", description: "Diagnose für die Controlling-Quelle: GET /api/intern-analytics/diag Liefert: - SHOW TABLES (auf dem aktiven Account) - Probe-Selects mit FROM key_analytics, FROM api_analytics und FROM <controll_platform_logs> (dedicated Tabellenname) Hinweis: Cloudflare Pages routet keine Dateien, deren Name mit `_` beginnt – daher heißt diese Datei `diag.ts`, nicht `_diag.ts`." },
  { path: "/api/intern-analytics/image-url-requests-customer-arcs", methods: ["GET"], source: "functions/api/intern-analytics/image-url-requests-customer-arcs.ts", description: "GET /api/intern-analytics/image-url-requests-customer-arcs Sammelt Customer-Datensätze (D1: `customers`), bei denen sowohl `company` als auch `location` (ISO-2; Legacy: Spalte `standort`) gesetzt sind, und holt aus der Analytics Engine das Country-Breakdown pro `index1`-Domain – damit auf der Bildaustrahlungs-Karte ein Bogen vom Firmensitz zu jedem Viewer-Land gezeichnet werden kann. Query: from, to, days (wie geo-Endpoint). Response: ``` { from, to, days, modesTried, customers: [{ id, email, company, location, //" },
  { path: "/api/intern-analytics/image-url-requests-geo", methods: ["GET"], source: "functions/api/intern-analytics/image-url-requests-geo.ts", description: "GET /api/intern-analytics/image-url-requests-geo Analytics Engine: Stream `image_url_requests` (oder dedizierte Tabelle gleichen Namens). Länder: `blob3` (ISO-2, z. B. GB). Domains: `index1` (Kunden-Hosts). Zählung: SUM(_sample_interval) wie in den anderen AE-Auswertungen. Query: from, to (YYYY-MM-DD HH:MM:SS, UTC), `days` (1–400), `diagnose=1` (Volumen pro Quelle/Modus + tatsächliche `dataset`-Werte). Hinweis: die Analytics-Engine-SQL-API unterstützt hier kein `TRIM()` / `UPPER()` um Spalten (422). Nackte `blob3`-" },
  { path: "/api/intern-analytics/image-url-requests-ip-breakdown", methods: ["GET"], source: "functions/api/intern-analytics/image-url-requests-ip-breakdown.ts", description: "GET /api/intern-analytics/image-url-requests-ip-breakdown Aggregiert Bild-URL-Requests aus Analytics Engine `image_url_requests` nach Client-IP und Land (`blob3` = ISO-2), analog zu `image-url-requests-geo`. Die Client-IP liegt im Bildaustrahlungs-Worker in `blob4` (Standard). Per Env `IMAGE_URL_REQUESTS_IP_BLOB` umschaltbar: `blob1` | `blob2` | `blob4`. Query: `days` (1–400), optional `from` / `to` (wie Geo-Endpoint). Response: sortierte Liste mit IP, ISO-2, Zählung, Klassifikation v4/v6, optional: `avgMs` aus `do" },
  { path: "/api/intern-analytics/user-analytics", methods: ["GET"], source: "functions/api/intern-analytics/user-analytics.ts", description: "GET /api/intern-analytics/user-analytics Liefert Auswertung der AE-Tabelle `controll_platform_logs` aus User-Sicht. Ohne `user`-Parameter: nur Liste aller User im Zeitraum (Sidebar). Mit `user`-Parameter: zusätzlich detaillierter Bericht. Mit `user` + `ip`: Detail-Bericht eingeschränkt auf eine IP. Query-Parameter: from, to – YYYY-MM-DD HH:MM:SS (Standard: letzte 30 Tage) user – optional: index1 / Username ip – optional: blob5 / IP des Users gapMinutes – Sessions-Trennung (Standard: 5) limit – max. Zeilen aus AE (S" },
  { path: "/api/login", methods: ["POST"], source: "functions/api/login.ts", description: "Anmeldung mit Benutzername und Passwort. Setzt bei Erfolg das Session-Cookie, oder liefert Hinweise auf ausstehendes TOTP, Passwort-Erstsetup oder Fehler." },
  { path: "/api/login-totp", methods: ["POST"], source: "functions/api/login-totp.ts", description: "Zweiter Login-Schritt nach TOTP: verifiziert Einmalcode und mfaPendingToken und stellt bei Erfolg die Session ein." },
  { path: "/api/logout", methods: ["POST"], source: "functions/api/logout.ts", description: "Beendet die Sitzung: Session-Cookie wird gelöscht (leerer Wert, abgelaufen)." },
  { path: "/api/mapping", methods: ["GET", "POST", "PUT", "DELETE"], source: "functions/api/mapping.ts", description: "POST /api/mapping Body: { \"table\": \"...\", \"row\": { ... } } (ohne id) PUT /api/mapping Body: { \"table\", \"id\", \"row\" } GET /api/mapping?table=...&limit=&offset=&q= DELETE /api/mapping?table=...&id=..." },
  { path: "/api/me", methods: ["GET"], source: "functions/api/me.ts", description: "Liefert den aktuellen Benutzer (Profilfelder) und die Liste erlaubter SPA-Pfade (`erlaubtePfade`) für die Sicherheitsstufe." },
  { path: "/api/mfa/disable", methods: ["POST"], source: "functions/api/mfa/disable.ts", description: "Deaktiviert TOTP nach Passwortprüfung (nicht erlaubt, wenn das Konto 2FA verpflichtend hat)." },
  { path: "/api/mfa/enroll-confirm", methods: ["POST"], source: "functions/api/mfa/enroll-confirm.ts", description: "Bestätigt TOTP-Einrichtung: prüft den 6-stelligen Code und aktiviert Zwei-Faktor für das Konto." },
  { path: "/api/mfa/enroll-start", methods: ["POST"], source: "functions/api/mfa/enroll-start.ts", description: "Startet TOTP-Einrichtung: erzeugt Secret, speichert es vorläufig und liefert Daten für den Authenticator (otpauth-URI)." },
  { path: "/api/mfa/status", methods: ["GET"], source: "functions/api/mfa/status.ts", description: "Liefert den 2FA-Status des Kontos (TOTP aktiv, Secret vorhanden, Verifizierung, ob Admin 2FA erzwingt)." },
  { path: "/api/overview/stats", methods: ["GET"], source: "functions/api/overview/stats.ts", description: "GET /api/overview/stats Aggregiert Kennzahlen für die Dashboard-Übersicht (D1 website, D1 controll_status, optional KV `customer_keys`). Liefert eine 30-Tage-Tageszeitreihe (UTC) inkl. Lückenfüllung. Tabellen ohne `created_at` schlagen mit leerer Liste zurück. Tag = heute (UTC), Woche = rollierend 7 Tage, Monat = laufender Kalendermonat (UTC)." },
  { path: "/api/setup-password", methods: ["GET", "POST"], source: "functions/api/setup-password.ts", description: "Diagnose-Endpunkt: zeigt, ob Cloudflare Pages Functions die Variable `password_secret` aktuell sehen können — ohne den Wert auszuliefern. Aufruf z.B. im Browser: `GET /api/setup-password`. Antwort enthält Namen und Längen, aber niemals den Pepper selbst. Sicher: WebCrypto/PBKDF2-Fehlermeldungen enthalten weder Pepper noch User-Passwort, sondern nur Operationen (\"PBKDF2 not supported\", \"Worker exceeded CPU time\" o.ae.). Hilft, Cloudflare-Limits/-Setup- Probleme zu erkennen, ohne in Logs schauen zu muessen." },
  { path: "/api/system/blocked-vehicles", methods: ["GET", "PUT"], source: "functions/api/system/blocked-vehicles.ts", description: "GET /api/system/blocked-vehicles Liefert die Konfiguration aus KV-Key `_config_blocked_vehicles` (fehlend = leer). PUT /api/system/blocked-vehicles Body: { \"value\": { \"brands\": string[], \"models\": string[] } }" },
  { path: "/api/system/prompts", methods: ["GET", "PUT"], source: "functions/api/system/prompts.ts", description: "GET /api/system/prompts Ohne Query: alle Keys auflisten. ?key=front_right: JSON lesen. PUT /api/system/prompts Body: { \"key\": \"front_right\", \"value\": { ... } }" },
  { path: "/api/system/seed-missing-view-regen-status", methods: ["GET", "POST"], source: "functions/api/system/seed-missing-view-regen-status.ts", description: "GET /api/system/seed-missing-view-regen-status?slug=dashboard|center_console POST /api/system/seed-missing-view-regen-status Body: { slug: \\\"…\\\" } Nur Slugs aus `SEED_MISSING_VIEW_SLUGS`. Siehe `_lib/seedMissingViewRegenStatus`." },
  { path: "/api/vehicle-imagery/catalog", methods: ["GET"], source: "functions/api/vehicle-imagery/catalog.ts", description: "GET /api/vehicle-imagery/catalog Nur SELECT: Distinct-Werte und geparste Ansichten. Optional ?marke= & ?modell=. Optional: &rows=1&limit=50&offset=0 — Zeilen (max. 500)." },
  { path: "/api/website/newsletter", methods: ["GET"], source: "functions/api/website/newsletter.ts", description: "GET /api/website/newsletter D1 `website` → Tabelle `newsletter` (nur SELECT). Query: q, limit, offset, active=all|0|1" },
  { path: "/api/website/submissions", methods: ["GET", "PATCH"], source: "functions/api/website/submissions.ts", description: "GET /api/website/submissions D1 `website` → Tabelle `submissions` (nur SELECT). Query: q, limit, offset, spam=all|0|1, ansicht=offen|alle (Standard: nur offene, erledigt=0) PATCH Body: { id: string, erledigt: 0 | 1 }" },
  { path: "/api/website/submissions-by-country", methods: ["GET"], source: "functions/api/website/submissions-by-country.ts", description: "GET /api/website/submissions-by-country D1 `website` → `submissions`: Aggregation nach Ländercode in `metadata.country` (ISO-2, z. B. DE). Nur Nicht-Spam: IFNULL(spam,0) = 0" },
  { path: "/api/website/trial-submissions", methods: ["GET", "PATCH"], source: "functions/api/website/trial-submissions.ts", description: "GET /api/website/trial-submissions PATCH /api/website/trial-submissions D1 `website` → Tabelle `trial_submissions`. Query: q, limit, offset, spam=all|0|1, ansicht=offen|alle (Standard: nur offene) PATCH Body: { id: string, erledigt: 0 | 1 }" },
];
